In [ ]:
UNDERSTANDING PYTHON INTRODUCTION

In [ ]:
#Example of How to Create Dictionary Variable Data Type

ClubEropa = {"nama_club" : ["Real Madrid", "FC Twente", "Inter Milan", "Bayern Munchen"], 
             "pelatih_club": ["Carlo Ancelloti", "Gonzalo Garcia", "Simone Inzaghi", "Julian Nagelsmann"], 
             "Negara":["Spanyol", "Belanda", "Italia", "Jerman"], 
             "Pemain": ["Karim Benzema", "Wout Brama", "Hakan Calhanoglu", "Robert Lewandowski"]}

print(ClubEropa["nama_club"])
print(ClubEropa["pelatih_club"])
print(ClubEropa["Negara"])
print(ClubEropa["Pemain"])

['Real Madrid', 'FC Twente', 'Inter Milan', 'Bayern Munchen']
['Carlo Ancelloti', 'Gonzalo Garcia', 'Simone Inzaghi', 'Julian Nagelsmann']
['Spanyol', 'Belanda', 'Italia', 'Jerman']
['Karim Benzema', 'Wout Brama', 'Hakan Calhanoglu', 'Robert Lewandowski']


In [ ]:
#Example of How to Add 'Key' Data Type to the Existed Variable

sponsor_ClubEropa = {"sponsor" : ["Fly Emirates", "Apparel Meyba", "socios.com", "Deutsche Telekom"]}

ClubEropa.update(sponsor_ClubEropa)

print(ClubEropa)

{'nama_club': ['Real Madrid', 'FC Twente', 'Inter Milan', 'Bayern Munchen'], 'pelatih_club': ['Carlo Ancelloti', 'Gonzalo Garcia', 'Simone Inzaghi', 'Julian Nagelsmann'], 'Negara': ['Spanyol', 'Belanda', 'Italia', 'Jerman'], 'Pemain': ['Karim Benzema', 'Wout Brama', 'Hakan Calhanoglu', 'Robert Lewandowski'], 'sponsor': ['Fly Emirates', 'Apparel Meyba', 'socios.com', 'Deutsche Telekom']}


In [ ]:
#Example of How to Create Array Variable 

import numpy as np
transaksi_2018 = np.array([243, 254, 265, 276, 287])
transaksi_2019 = np.array([324, 345, 352, 355, 362])
transaksi_2020 = np.array([413, 423, 434, 454, 464])
transaksi_2021 = np.array([568, 579, 580, 598, 600])

In [ ]:
#Example of How to Multipliy Array Variable
print(transaksi_2018*transaksi_2020)

[100359 107442 115010 125304 133168]


In [ ]:
#Example of How to Sum Up Array Variable
print(transaksi_2019+transaksi_2021)

[892 924 932 953 962]


In [ ]:
#Example of How to Know Intersection of Variable
print(np.intersect1d(transaksi_2018, transaksi_2021))

[]


In [ ]:
#Example of How to Know Index of The List Variable
print(transaksi_2019[0])
print(transaksi_2019[2])
print(transaksi_2019[4])

324
352
362


In [ ]:
#Example of How to Substract Array Variable
import numpy as np

nilai_kelas = np.array([[80, 85, 75, 80], 
                        [70, 90, 85, 70],
                        [75, 80, 95, 85],
                        [95, 85, 75, 70]])

nilai_menyontek = 5

print(nilai_kelas - nilai_menyontek)

[[75 80 70 75]
 [65 85 80 65]
 [70 75 90 80]
 [90 80 70 65]]


Python merupakan bahasa pemrograman yang dikembangkan oleh Guido Van Rossum pada tahun 1991
dan terus mengalami pembaruan sampai saat ini. Python merupakan bahasa pemrograman yang banyak 
digunakan untuk mengembangkan situs web, melakukan proses otomatisasi, membuat game, aplikasi, 
bahkan data analisis, maka dari itu python disebut sebagai bahasa pemrograman yang general-multipurpose,
serta termasuk dalam 3 besar bahasa pemrograman yang digunakan dalam beberapa tahun terakhir.

Python memiliki bahasa pemrograman yang lebih ringkas dan sederhana sehingga kodenya dapat lebih mudah 
dipahami serta memberikan kemudahan bagi developer. Python juga bersifat open source dimana programnya 
mudah diakses untuk dipelajari dan dikembangkan serta memiliki package atau library yang memudahkan 
data scientist atau machine learning engineer dalam mengolah dan menganalisis data seperti Sci-kit Learn, 
TensorFlow, dan PyTorch. 

Python juga salah satu bahasa pemrograman yang banyak digunakan dan berkaitan dengan data science dan 
machine learning karena keunggulan python untuk proses prototyping dan scripting. Beberapa manfaat dan 
keunggulan bahasa pemrograman python yakni memiliki sintaksis yang sederhana dan mirip dengan bahasa inggris, 
serta ringkas apabila dibandingkan dengan bahasa pemrograman lain serta fleksibel dimana dapat dioperasikan 
pada berbagai sistem operasi. Selain itu python juga mendukung ekosistem Internet of Things. 